spring:
  datasource:
#    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: miffymiffymiffymiffymiffymiffymiffymiffy